# Change these first
owner: fixator10 # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: Fixator10
    url: https://fixator10.ru
  - name: "Ene: static"
    url: https://ene.fixator10.ru
  - name: "Ene: dashboard"
    url: https://enedash.fixator10.ru

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.fixator10.ru
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Idk what is this"
  introMessage: This is supposed to be a status page, but not sure yet
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
