# Change these first
owner: fixator10 # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: Fixator10
    url: https://fixator10.ru
  - name: "Ene: Static"
    url: https://ene.fixator10.ru
    icon: https://cdn.discordapp.com/avatars/257789498153238528/0b3b9d6b02bddc804d831ad919c2e36e.png?size=128
  - name: "Ene: Stats (Grafana)"
    url: https://ene.fixator10.ru/stats/api/health
    icon: https://grafana.com/static/assets/img/fav32.png
  - name: "Ene: Stats (DB)"
    url: $SECRET_SITE_1
    icon: https://www.influxdata.com/wp-content/uploads/Favicon-blue-200x200.png
  - name: "Ene: Dashboard"
    url: https://ene.fixator10.ru/dash/
    icon: https://cdn.discordapp.com/avatars/257789498153238528/0b3b9d6b02bddc804d831ad919c2e36e.png?size=128
    
assignees: # Users to assign downtime issues (optional)
  - Fixator10

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: status.fixator10.ru
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /status
  logoUrl: https://gravatar.com/avatar/cc1b58943b87cd3b8ac447b69caaf109?s=2048
  name: Fixator10 status page
  introTitle: "My personal status page"
  introMessage: "I guess, i'm still alive. *Probably...* Look below."
  theme: dark
  navbar:
    - title: Home
      href: https://fixator10.ru/
    - title: Ene
      href: https://ene.fixator10.ru/
    - title: Status
      href: /
      
notifications:
  - type: discord

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
