# Change these first
owner: fixator10 # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: Fixator10
    url: https://fixator10.ru
  - name: "Ene: static"
    url: https://ene.fixator10.ru
  - name: "Ene: stats (grafana)"
    url: https://ene.fixator10.ru/stats/api/health
  - name: "Ene: stats (db)"
    url: $SECRET_SITE_1
  - name: "Ene: dashboard"
    url: https://enedash.fixator10.ru

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.fixator10.ru
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://gravatar.com/avatar/cc1b58943b87cd3b8ac447b69caaf109?s=2048
  name: Fixator10 status page
  introTitle: "My personal status page"
  introMessage: "I guess, i'm still alive. Probably... Look below."
  navbar:
    - title: Home
      href: https://fixator10.ru/
    - title: Ene
      href: https://ene.fixator10.ru/
    - title: Status
      href: /
      
notifications:
  - type: discord

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
